# Generated by Django 2.2 on 2023-04-30 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatCompletionWithoutContext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=2048)),
                ('prompt', models.CharField(blank=True, max_length=4096)),
                ('completion', models.TextField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '聊天记录管理-无上下文关联',
                'verbose_name_plural': '聊天记录管理-无上下文关联',
                'db_table': 'tb_chat_completion_without_context',
            },
        ),
    ]
