# Generated by Django 2.2 on 2023-04-29 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='totoal_views',
            new_name='total_views',
        ),
    ]
